In [1]:
import pandas as pd
import numpy as np

In [3]:
df_up = pd.read_csv('data/서울특별시 공공자전거 대여소별 이용정보(월별)_25.1-6.csv')
df_up.head()

   자치구               대여소명    기준년월  대여건수  반납건수
0  마포구       108. 서교동 사거리  202501   670   786
1  양천구   729. 서부식자재마트 건너편  202501   961   939
2  양천구  731. 서울시 도로환경관리센터  202501  1671  1722
3  양천구   733. 신정이펜하우스314동  202501   299   154
4  양천구      734. 신트리공원 입구  202501  1555  1549

In [5]:
df_down = pd.read_csv('data/서울특별시 공공자전거 대여소별 이용정보(월별)_25.7-12.csv')
df_down.head()

   자치구               대여소명    기준년월  대여건수  반납건수
0  마포구       108. 서교동 사거리  202507  1277  1314
1  양천구   729. 서부식자재마트 건너편  202507  1658  1808
2  양천구  731. 서울시 도로환경관리센터  202507  3135  3218
3  양천구   733. 신정이펜하우스314동  202507   876   375
4  양천구      734. 신트리공원 입구  202507  2987  2958

In [6]:
df_up.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16407 entries, 0 to 16406
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     16407 non-null  object
 1   대여소명    16407 non-null  object
 2   기준년월    16407 non-null  int64
 3   대여건수    16407 non-null  int64
 4   반납건수    16407 non-null  int64
dtypes: int64(3), object(2)
memory usage: 641.0+ KB

In [7]:
df_down.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16568 entries, 0 to 16567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     16568 non-null  object
 1   대여소명    16568 non-null  object
 2   기준년월    16568 non-null  int64
 3   대여건수    16568 non-null  int64
 4   반납건수    16568 non-null  int64
dtypes: int64(3), object(2)
memory usage: 647.3+ KB

In [9]:
print(df_up.isna().sum())
print('-' * 30)
print(df_down.isna().sum())

자치구     0
대여소명    0
기준년월    0
대여건수    0
반납건수    0
dtype: int64
------------------------------
자치구     0
대여소명    0
기준년월    0
대여건수    0
반납건수    0
dtype: int64

In [13]:
df_up[['대여소번호', '대여소']] = df_up['대여소명'].str.extract(r'^(\d+)\.\s*(.*)$')
df_up['대여소번호'] = pd.to_numeric(
    df_up['대여소번호'],
    errors='coerce'
)

df_up['대여소'] = df_up['대여소'].str.strip()

df_up.head()

   자치구               대여소명    기준년월  대여건수  반납건수  대여소번호           대여소
0  마포구       108. 서교동 사거리  202501   670   786  108.0       서교동 사거리
1  양천구   729. 서부식자재마트 건너편  202501   961   939  729.0   서부식자재마트 건너편
2  양천구  731. 서울시 도로환경관리센터  202501  1671  1722  731.0  서울시 도로환경관리센터
3  양천구   733. 신정이펜하우스314동  202501   299   154  733.0   신정이펜하우스314동
4  양천구      734. 신트리공원 입구  202501  1555  1549  734.0      신트리공원 입구

In [14]:
df_up = df_up.drop('대여소명', axis=1)

In [15]:
df_up.head()

   자치구    기준년월  대여건수  반납건수  대여소번호           대여소
0  마포구  202501   670   786  108.0       서교동 사거리
1  양천구  202501   961   939  729.0   서부식자재마트 건너편
2  양천구  202501  1671  1722  731.0  서울시 도로환경관리센터
3  양천구  202501   299   154  733.0   신정이펜하우스314동
4  양천구  202501  1555  1549  734.0      신트리공원 입구

In [16]:
df_up['대여소번호'] = df_up['대여소번호'].astype('Int64')
df_up.head()

   자치구    기준년월  대여건수  반납건수  대여소번호           대여소
0  마포구  202501   670   786    108       서교동 사거리
1  양천구  202501   961   939    729   서부식자재마트 건너편
2  양천구  202501  1671  1722    731  서울시 도로환경관리센터
3  양천구  202501   299   154    733   신정이펜하우스314동
4  양천구  202501  1555  1549    734      신트리공원 입구

In [17]:
df_down[['대여소번호', '대여소']] = df_down['대여소명'].str.extract(r'^(\d+)\.\s*(.*)$')
df_down['대여소번호'] = pd.to_numeric(
    df_up['대여소번호'],
    errors='coerce'
)

df_down['대여소'] = df_down['대여소'].str.strip()
df_down = df_down.drop('대여소명', axis=1)

df_down['대여소번호'] = df_down['대여소번호'].astype('Int64')
df_down.head()

   자치구    기준년월  대여건수  반납건수  대여소번호           대여소
0  마포구  202507  1277  1314    108       서교동 사거리
1  양천구  202507  1658  1808    729   서부식자재마트 건너편
2  양천구  202507  3135  3218    731  서울시 도로환경관리센터
3  양천구  202507   876   375    733   신정이펜하우스314동
4  양천구  202507  2987  2958    734      신트리공원 입구

In [18]:
df_up.to_csv('data/2025년_상반기_공공자전거_이용데이터_1-6.csv', index=False, encoding='utf-8-sig')
df_down.to_csv('data/2025년_하반기_공공자전거_이용데이터_7-12.csv', index=False, encoding='utf-8-sig')

print('데이터 출력 완료!')

데이터 출력 완료!

In [19]:
df_up.shape

(16407, 6)

In [20]:
df_down.shape

(16568, 6)