In [1]:
import pandas as pd
import numpy as np

print('출력완료')

출력완료

In [167]:
df_month = pd.read_csv('data/서울특별시 공공자전거 대여소별 이용정보(월별)_26.1-6.csv')
df_month.head()

   자치구                            대여소명    기준년월  대여건수  반납건수
0  강남구                2301. 현대고등학교 건너편  202601   154   183
1  강남구  2302. 교보타워 버스정류장(신논현역 3번출구 후면)  202601   467   492
2  강남구                 2303. 논현역 10번출구  202601   501   332
3  강남구                    2304. 대현그린타워  202601    79    44
4  강남구              2305. MCM 본사 직영점 앞  202601   149   177

In [168]:
df_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16624 entries, 0 to 16623
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     16624 non-null  object
 1   대여소명    16624 non-null  object
 2   기준년월    16624 non-null  int64
 3   대여건수    16624 non-null  int64
 4   반납건수    16624 non-null  int64
dtypes: int64(3), object(2)
memory usage: 649.5+ KB

In [169]:
df_month.isna().sum()

자치구     0
대여소명    0
기준년월    0
대여건수    0
반납건수    0
dtype: int64

In [50]:
# 월별, 서울 주요 따릉이 대여소
# df_month 는 아래의 코드로 대여건수와 반납건수를 기준으로 내림차순으로 정렬된 데이터 프레임

In [187]:
df_date = pd.read_csv('data/서울특별시 공공자전거 이용정보(일별)_2606.csv')
df_date.head()

,대여일자,대여소번호,대여소,대여구분코드,성별,연령대,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,2026-06-01,736,736. 오솔길공원,정기권,NaN,~10대,1,42.99,0.39,1670.26,36
1,2026-06-01,939,939. 은평구청 교차로,정기권,NaN,~10대,1,39.05,0.35,1516.98,12
2,2026-06-01,1044,1044. 굽은다리역,정기권,NaN,~10대,1,67.58,0.61,2625.35,17
3,2026-06-01,1152,1152. 마곡역교차로,정기권,NaN,~10대,1,4.54,0.04,176.30,2
4,2026-06-01,2269,2269. 주홍교 하부,정기권,NaN,~10대,1,33.28,0.30,1293.01,11

In [188]:
df_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2107239 entries, 0 to 2107238
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   대여일자     object
 1   대여소번호    int64
 2   대여소      object
 3   대여구분코드   object
 4   성별       object
 5   연령대      object
 6    이용건수    int64
 7   운동량      float64
 8   탄소량      float64
 9   이동거리(M)  float64
 10  이용시간(분)  int64
dtypes: float64(3), int64(3), object(5)
memory usage: 176.8+ MB

In [189]:
df_date.isna().sum()
# 성별, 운동량, 탄소량은 웹 페이지에서 사용되지 않는 정보이기 때문에 제거해도 무방한 컬럼
# 별도로 대여구분코드에 대해서는 다른 데이터도 알아볼 필요가 있음
# 이외에도 대여소를 함축할 필요성이 있다고 봄

대여일자            0
대여소번호           0
대여소             0
대여구분코드          0
성별         592397
연령대             0
 이용건수           0
운동량          6137
탄소량          6137
이동거리(M)         0
이용시간(분)         0
dtype: int64

In [190]:
# 필요없는 컬럼 제거
df_date = df_date.drop(['성별', '운동량', '탄소량'], axis=1)
df_date

,대여일자,대여소번호,대여소,대여구분코드,연령대,이용건수,이동거리(M),이용시간(분)
0,2026-06-01,736,736. 오솔길공원,정기권,~10대,1,1670.26,36
1,2026-06-01,939,939. 은평구청 교차로,정기권,~10대,1,1516.98,12
2,2026-06-01,1044,1044. 굽은다리역,정기권,~10대,1,2625.35,17
3,2026-06-01,1152,1152. 마곡역교차로,정기권,~10대,1,176.30,2
4,2026-06-01,2269,2269. 주홍교 하부,정기권,~10대,1,1293.01,11
...,...,...,...,...,...,...,...,...
2107234,2026-06-30,4244,4244. 당인리발전소 공원 앞,일일권(비회원 3시간),기타,1,11114.88,251
2107235,2026-06-30,5515,5515.한강버스 망원 선착장,일일권(비회원 3시간),기타,1,3287.93,21
2107236,2026-06-30,5891,5891.한강버스 여의도 선착장,일일권(비회원 3시간),기타,3,55107.96,370
2107237,2026-06-30,195,195. 모래내고가차도,일일권(비회원 3시간),기타,1,6858.52,97
2107238,2026-06-30,1210,1210. 롯데월드타워(잠실역2번출구 쪽),일일권(비회원 3시간),기타,1,2448.62,39

In [191]:
print(df_date.columns.tolist())

['대여일자', '대여소번호', '대여소', '대여구분코드', '연령대', ' 이용건수', '이동거리(M)', '이용시간(분)']

In [192]:
df_date.columns = df_date.columns.str.strip()

In [193]:
print(df_date.columns.tolist())

['대여일자', '대여소번호', '대여소', '대여구분코드', '연령대', '이용건수', '이동거리(M)', '이용시간(분)']

In [194]:
# 날짜를 기준으로 이용건수가 가장 많은 대여소를 기준으로 정렬
df_date = df_date.groupby(['대여일자', '대여소번호', '대여소', '연령대', '이동거리(M)', '이용시간(분)'], as_index=False)['이용건수'].sum().sort_values(['대여일자', '이용건수'],ascending=[True, False]).groupby('대여일자').reset_index(drop=True)
df_date.head()

         대여일자  대여소번호                  대여소  연령대    이동거리(M)  이용시간(분)  이용건수
0  2026-06-01   2728     2728.마곡나루역 3번 출구  30대  102598.46      635    68
1  2026-06-01   2715    2715.마곡나루역 2번 출구   30대   53489.50      380    51
2  2026-06-01   1291     1291. 서울체육고등학교 앞  20대   68600.28      784    45
3  2026-06-01   2701  2701. 마곡나루역 5번출구 뒤편  40대   40283.67      306    41
4  2026-06-01   2717     2717.LG유플러스 마곡사옥  30대   49213.68      291    41

In [86]:
df_date['연령대'].value_counts()

연령대
30대     66
20대     50
40대     17
기타      13
~10대     4
Name: count, dtype: int64

In [210]:
df_time = pd.read_csv('data/서울특별시 공공자전거 이용정보(시간별)_202606.csv')
df_time.head()

,대여일자,대여시간,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,2026-06-01,0,1028,1028. 포레스 주상복합 빌딩,정기권,NaN,20대,1,19.81,0.18,769.67,4
1,2026-06-01,0,1150,1150. 송정역 1번출구,정기권,NaN,20대,1,39.88,0.36,1549.49,9
2,2026-06-01,0,1535,1535. 효성인텔리안 앞,정기권,NaN,20대,1,22.14,0.20,860.08,6
3,2026-06-01,0,1650,1650. 중계근린공원내,정기권,NaN,20대,1,13.12,0.12,509.69,6
4,2026-06-01,0,2271,2271. 내방역 8번출구 앞,정기권,NaN,20대,1,23.97,0.22,931.08,8

In [146]:
df_rental = pd.read_excel('data/공공자전거 대여소 정보(26.6월 기준).xlsx', header=None)
df_rental.head(4)

         0          1        2     3    4    5       6       7       8       9
0  대여소\n번호  보관소(대여소)명  소재지(위치)   NaN  NaN  NaN  설치\n시기    설치형태     NaN  운영\n방식
1      NaN        NaN      NaN   NaN  NaN  NaN     NaN     LCD      QR     NaN
2      NaN        NaN      자치구  상세주소   위도   경도     NaN     NaN     NaN     NaN
3      NaN        NaN      NaN   NaN  NaN  NaN     NaN  거치\n대수  거치\n대수     NaN

In [147]:
df_rental.shape

(2794, 10)

In [148]:
df_rental = df_rental.iloc[5:].copy().reset_index(drop=True)
df_rental.head()

,0,1,2,3,4,5,6,7,8,9
0,102,망원역 1번출구 앞,마포구,서울특별시 마포구 월드컵로 72,37.555649,126.910629,2015-09-06 23:42:06,NaN,15,QR
1,103,망원역 2번출구 앞,마포구,서울특별시 마포구 월드컵로 79,37.554951,126.910835,2015-09-06 23:43:13,NaN,14,QR
2,104,합정역 1번출구 앞,마포구,서울특별시 마포구 양화로 59,37.550629,126.914986,2015-09-06 23:44:31,NaN,13,QR
3,105,합정역 5번출구 앞,마포구,서울특별시 마포구 양화로 48,37.550007,126.914825,2015-09-06 23:45:30,NaN,5,QR
4,106,합정역 7번출구 앞,마포구,서울특별시 마포구 독막로 4,37.548645,126.912827,2015-09-06 23:46:31,NaN,12,QR

In [149]:
df_rental.columns = ['대여소번호', '대여소', '자치구', '상세주소', '위도', '경도', '설치시기', '설치형태', '거치대수', '운영방식']
df_rental.head()

,대여소번호,대여소,자치구,상세주소,위도,경도,설치시기,설치형태,거치대수,운영방식
0,102,망원역 1번출구 앞,마포구,서울특별시 마포구 월드컵로 72,37.555649,126.910629,2015-09-06 23:42:06,NaN,15,QR
1,103,망원역 2번출구 앞,마포구,서울특별시 마포구 월드컵로 79,37.554951,126.910835,2015-09-06 23:43:13,NaN,14,QR
2,104,합정역 1번출구 앞,마포구,서울특별시 마포구 양화로 59,37.550629,126.914986,2015-09-06 23:44:31,NaN,13,QR
3,105,합정역 5번출구 앞,마포구,서울특별시 마포구 양화로 48,37.550007,126.914825,2015-09-06 23:45:30,NaN,5,QR
4,106,합정역 7번출구 앞,마포구,서울특별시 마포구 독막로 4,37.548645,126.912827,2015-09-06 23:46:31,NaN,12,QR

In [150]:
df_rental.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2789 entries, 0 to 2788
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대여소번호   2789 non-null   object
 1   대여소     2789 non-null   object
 2   자치구     2789 non-null   object
 3   상세주소    2789 non-null   object
 4   위도      2789 non-null   object
 5   경도      2789 non-null   object
 6   설치시기    2789 non-null   object
 7   설치형태    1055 non-null   object
 8   거치대수    1740 non-null   object
 9   운영방식    2789 non-null   object
dtypes: object(10)
memory usage: 218.0+ KB

In [151]:
df_rental.isna().sum()

대여소번호       0
대여소         0
자치구         0
상세주소        0
위도          0
경도          0
설치시기        0
설치형태     1734
거치대수     1049
운영방식        0
dtype: int64

In [152]:
df_rental['위도'] = pd.to_numeric(df_rental['위도'], errors='coerce')
df_rental['경도'] = pd.to_numeric(df_rental['경도'], errors='coerce')
df_rental['거치대수'] = pd.to_numeric(df_rental['거치대수'], errors='coerce')

In [153]:
df_rental.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2789 entries, 0 to 2788
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대여소번호   2789 non-null   object
 1   대여소     2789 non-null   object
 2   자치구     2789 non-null   object
 3   상세주소    2789 non-null   object
 4   위도      2789 non-null   float64
 5   경도      2789 non-null   float64
 6   설치시기    2789 non-null   object
 7   설치형태    1055 non-null   object
 8   거치대수    1740 non-null   float64
 9   운영방식    2789 non-null   object
dtypes: float64(3), object(7)
memory usage: 218.0+ KB

In [154]:
df_rental.head()

,대여소번호,대여소,자치구,상세주소,위도,경도,설치시기,설치형태,거치대수,운영방식
0,102,망원역 1번출구 앞,마포구,서울특별시 마포구 월드컵로 72,37.555649,126.910629,2015-09-06 23:42:06,NaN,15.0,QR
1,103,망원역 2번출구 앞,마포구,서울특별시 마포구 월드컵로 79,37.554951,126.910835,2015-09-06 23:43:13,NaN,14.0,QR
2,104,합정역 1번출구 앞,마포구,서울특별시 마포구 양화로 59,37.550629,126.914986,2015-09-06 23:44:31,NaN,13.0,QR
3,105,합정역 5번출구 앞,마포구,서울특별시 마포구 양화로 48,37.550007,126.914825,2015-09-06 23:45:30,NaN,5.0,QR
4,106,합정역 7번출구 앞,마포구,서울특별시 마포구 독막로 4,37.548645,126.912827,2015-09-06 23:46:31,NaN,12.0,QR

In [155]:
df_rental = df_rental.drop(['설치시기', '설치형태', '운영방식', '상세주소'], axis=1)

In [156]:
df_rental.head()

  대여소번호          대여소  자치구         위도          경도  거치대수
0   102   망원역 1번출구 앞  마포구  37.555649  126.910629  15.0
1   103   망원역 2번출구 앞  마포구  37.554951  126.910835  14.0
2   104   합정역 1번출구 앞  마포구  37.550629  126.914986  13.0
3   105   합정역 5번출구 앞  마포구  37.550007  126.914825   5.0
4   106   합정역 7번출구 앞  마포구  37.548645  126.912827  12.0

In [157]:
df_rental['대여소번호'].duplicated().sum()

np.int64(0)

In [158]:
df_rental.isna().sum()

대여소번호       0
대여소         0
자치구         0
위도          0
경도          0
거치대수     1049
dtype: int64

In [161]:
df_rental['거치대수'].describe()

count    1740.000000
mean       11.866667
std         6.058516
min         2.000000
25%         9.000000
50%        10.000000
75%        14.000000
max        62.000000
Name: 거치대수, dtype: float64

In [174]:
df_rental['거치대수'] = df_rental['거치대수'].fillna(df_rental['거치대수'].median())
df_rental.isna().sum()

대여소번호    0
대여소      0
자치구      0
위도       0
경도       0
거치대수     0
dtype: int64

In [177]:
df_month.head()

   자치구                            대여소명    기준년월  대여건수  반납건수
0  강남구                2301. 현대고등학교 건너편  202601   154   183
1  강남구  2302. 교보타워 버스정류장(신논현역 3번출구 후면)  202601   467   492
2  강남구                 2303. 논현역 10번출구  202601   501   332
3  강남구                    2304. 대현그린타워  202601    79    44
4  강남구              2305. MCM 본사 직영점 앞  202601   149   177

In [182]:
df_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16624 entries, 0 to 16623
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구     16624 non-null  object
 1   대여소명    16624 non-null  object
 2   기준년월    16624 non-null  int64
 3   대여건수    16624 non-null  int64
 4   반납건수    16624 non-null  int64
dtypes: int64(3), object(2)
memory usage: 649.5+ KB

In [183]:
# df_month['대여소명'].str.split('.', expand=True).apply(lambda x: x.str.strip())
df_month[['대여소번호', '대여소']] = df_month['대여소명'].str.extract(
    r'^(\d+)\.\s*(.*)$'
)

df_month['대여소번호'] = pd.to_numeric(
    df_month['대여소번호'],
    errors='coerce'
)

df_month['대여소'] = df_month['대여소'].str.strip()

df_month.head()

,자치구,대여소명,기준년월,대여건수,반납건수,대여소번호,대여소
0,강남구,2301. 현대고등학교 건너편,202601,154,183,2301,현대고등학교 건너편
1,강남구,2302. 교보타워 버스정류장(신논현역 3번출구 후면),202601,467,492,2302,교보타워 버스정류장(신논현역 3번출구 후면)
2,강남구,2303. 논현역 10번출구,202601,501,332,2303,논현역 10번출구
3,강남구,2304. 대현그린타워,202601,79,44,2304,대현그린타워
4,강남구,2305. MCM 본사 직영점 앞,202601,149,177,2305,MCM 본사 직영점 앞

In [184]:
df_month = df_month.drop('대여소명', axis=1)
df_month.head()

   자치구    기준년월  대여건수  반납건수  대여소번호                       대여소
0  강남구  202601   154   183   2301                현대고등학교 건너편
1  강남구  202601   467   492   2302  교보타워 버스정류장(신논현역 3번출구 후면)
2  강남구  202601   501   332   2303                 논현역 10번출구
3  강남구  202601    79    44   2304                    대현그린타워
4  강남구  202601   149   177   2305              MCM 본사 직영점 앞

In [195]:
df_date.head()

         대여일자  대여소번호                  대여소  연령대    이동거리(M)  이용시간(분)  이용건수
0  2026-06-01   2728     2728.마곡나루역 3번 출구  30대  102598.46      635    68
1  2026-06-01   2715    2715.마곡나루역 2번 출구   30대   53489.50      380    51
2  2026-06-01   1291     1291. 서울체육고등학교 앞  20대   68600.28      784    45
3  2026-06-01   2701  2701. 마곡나루역 5번출구 뒤편  40대   40283.67      306    41
4  2026-06-01   2717     2717.LG유플러스 마곡사옥  30대   49213.68      291    41

In [196]:
# df_date = df_month.drop('대여소번호', axis=1)
df_date[['대여소번호', '대여소']] = df_date['대여소'].str.extract(
    r'^(\d+)\.\s*(.*)$'
)

df_date['대여소번호'] = pd.to_numeric(
    df_month['대여소번호'],
    errors='coerce'
)

df_date['대여소'] = df_date['대여소'].str.strip()

df_date.head()

         대여일자  대여소번호            대여소  연령대    이동거리(M)  이용시간(분)  이용건수
0  2026-06-01   2301    마곡나루역 3번 출구  30대  102598.46      635    68
1  2026-06-01   2302    마곡나루역 2번 출구  30대   53489.50      380    51
2  2026-06-01   2303     서울체육고등학교 앞  20대   68600.28      784    45
3  2026-06-01   2304  마곡나루역 5번출구 뒤편  40대   40283.67      306    41
4  2026-06-01   2305    LG유플러스 마곡사옥  30대   49213.68      291    41

In [211]:
df_time.head()

,대여일자,대여시간,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,2026-06-01,0,1028,1028. 포레스 주상복합 빌딩,정기권,NaN,20대,1,19.81,0.18,769.67,4
1,2026-06-01,0,1150,1150. 송정역 1번출구,정기권,NaN,20대,1,39.88,0.36,1549.49,9
2,2026-06-01,0,1535,1535. 효성인텔리안 앞,정기권,NaN,20대,1,22.14,0.20,860.08,6
3,2026-06-01,0,1650,1650. 중계근린공원내,정기권,NaN,20대,1,13.12,0.12,509.69,6
4,2026-06-01,0,2271,2271. 내방역 8번출구 앞,정기권,NaN,20대,1,23.97,0.22,931.08,8

In [212]:
df_time[['대여소번호', '대여소']] = df_time['대여소명'].str.extract(
    r'^(\d+)\.\s*(.*)$'
)

df_time['대여소번호'] = pd.to_numeric(
    df_time['대여소번호'],
    errors='coerce'
)

df_time['대여소'] = df_time['대여소'].str.strip()
df_time = df_time.drop('대여소명', axis=1)

In [213]:
df_time.head()

,대여일자,대여시간,대여소번호,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분),대여소
0,2026-06-01,0,1028.0,정기권,NaN,20대,1,19.81,0.18,769.67,4,포레스 주상복합 빌딩
1,2026-06-01,0,1150.0,정기권,NaN,20대,1,39.88,0.36,1549.49,9,송정역 1번출구
2,2026-06-01,0,1535.0,정기권,NaN,20대,1,22.14,0.20,860.08,6,효성인텔리안 앞
3,2026-06-01,0,1650.0,정기권,NaN,20대,1,13.12,0.12,509.69,6,중계근린공원내
4,2026-06-01,0,2271.0,정기권,NaN,20대,1,23.97,0.22,931.08,8,내방역 8번출구 앞

In [214]:
df_time = df_time.drop(['성별', '운동량', '탄소량', '대여구분코드'], axis=1)
df_time.head()

         대여일자  대여시간   대여소번호 연령대코드  이용건수  이동거리(M)  이용시간(분)          대여소
0  2026-06-01     0  1028.0   20대     1   769.67        4  포레스 주상복합 빌딩
1  2026-06-01     0  1150.0   20대     1  1549.49        9     송정역 1번출구
2  2026-06-01     0  1535.0   20대     1   860.08        6     효성인텔리안 앞
3  2026-06-01     0  1650.0   20대     1   509.69        6      중계근린공원내
4  2026-06-01     0  2271.0   20대     1   931.08        8   내방역 8번출구 앞

In [215]:
df_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   대여일자     150 non-null    object
 1   대여소번호    150 non-null    int64
 2   대여소      150 non-null    object
 3   연령대      150 non-null    object
 4   이동거리(M)  150 non-null    float64
 5   이용시간(분)  150 non-null    int64
 6   이용건수     150 non-null    int64
dtypes: float64(1), int64(3), object(3)
memory usage: 8.3+ KB

In [216]:
df_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3660184 entries, 0 to 3660183
Data columns (total 8 columns):
 #   Column   Dtype
---  ------   -----
 0   대여일자     object
 1   대여시간     int64
 2   대여소번호    float64
 3   연령대코드    object
 4   이용건수     int64
 5   이동거리(M)  float64
 6   이용시간(분)  int64
 7   대여소      object
dtypes: float64(2), int64(3), object(3)
memory usage: 223.4+ MB

In [217]:
df_time.isna().sum()

대여일자        0
대여시간        0
대여소번호      10
연령대코드       0
이용건수        0
이동거리(M)     0
이용시간(분)     0
대여소        10
dtype: int64

In [218]:
df_time.shape

(3660184, 8)

In [219]:
df_time = df_time.dropna(subset=['대여소번호', '대여소'])
df_time.head()

         대여일자  대여시간   대여소번호 연령대코드  이용건수  이동거리(M)  이용시간(분)          대여소
0  2026-06-01     0  1028.0   20대     1   769.67        4  포레스 주상복합 빌딩
1  2026-06-01     0  1150.0   20대     1  1549.49        9     송정역 1번출구
2  2026-06-01     0  1535.0   20대     1   860.08        6     효성인텔리안 앞
3  2026-06-01     0  1650.0   20대     1   509.69        6      중계근린공원내
4  2026-06-01     0  2271.0   20대     1   931.08        8   내방역 8번출구 앞

In [220]:
df_time.tail()

               대여일자  대여시간   대여소번호 연령대코드  이용건수  이동거리(M)  이용시간(분)            대여소
3660179  2026-06-30    23  4217.0   20대     1  2832.43       82     한강공원 망원나들목
3660180  2026-06-30    23  4622.0   30대     1   586.79        7  한강중학교 앞 버스정류장
3660181  2026-06-30    23  4217.0   20대     1  2999.47       82     한강공원 망원나들목
3660182  2026-06-30    23  3759.0   30대     1   583.45        2         이대서울병원
3660183  2026-06-30    23  2368.0   40대     1   740.23        7  도곡동 경남아파트 건너편

In [229]:
df_rental.isna().sum()
df_rental.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2789 entries, 0 to 2788
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대여소번호   2789 non-null   object
 1   대여소     2789 non-null   object
 2   자치구     2789 non-null   object
 3   위도      2789 non-null   float64
 4   경도      2789 non-null   float64
 5   거치대수    2789 non-null   Int64
dtypes: Int64(1), float64(2), object(3)
memory usage: 133.6+ KB

In [228]:
df_rental['거치대수'] = df_rental['거치대수'].astype('Int64')

In [230]:
df_time['대여소번호'] = df_time['대여소번호'].astype('Int64')

In [231]:
df_time.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3660174 entries, 0 to 3660183
Data columns (total 8 columns):
 #   Column   Dtype
---  ------   -----
 0   대여일자     object
 1   대여시간     int64
 2   대여소번호    Int64
 3   연령대코드    object
 4   이용건수     int64
 5   이동거리(M)  float64
 6   이용시간(분)  int64
 7   대여소      object
dtypes: Int64(1), float64(1), int64(3), object(3)
memory usage: 254.8+ MB

In [222]:
# 최종 정리된 데이터 확인

In [237]:
df_month.head()

   자치구    기준년월  대여건수  반납건수  대여소번호                       대여소
0  강남구  202601   154   183   2301                현대고등학교 건너편
1  강남구  202601   467   492   2302  교보타워 버스정류장(신논현역 3번출구 후면)
2  강남구  202601   501   332   2303                 논현역 10번출구
3  강남구  202601    79    44   2304                    대현그린타워
4  강남구  202601   149   177   2305              MCM 본사 직영점 앞

In [233]:
df_date.head()

         대여일자  대여소번호            대여소  연령대    이동거리(M)  이용시간(분)  이용건수
0  2026-06-01   2301    마곡나루역 3번 출구  30대  102598.46      635    68
1  2026-06-01   2302    마곡나루역 2번 출구  30대   53489.50      380    51
2  2026-06-01   2303     서울체육고등학교 앞  20대   68600.28      784    45
3  2026-06-01   2304  마곡나루역 5번출구 뒤편  40대   40283.67      306    41
4  2026-06-01   2305    LG유플러스 마곡사옥  30대   49213.68      291    41

In [234]:
df_time.head()

         대여일자  대여시간  대여소번호 연령대코드  이용건수  이동거리(M)  이용시간(분)          대여소
0  2026-06-01     0   1028   20대     1   769.67        4  포레스 주상복합 빌딩
1  2026-06-01     0   1150   20대     1  1549.49        9     송정역 1번출구
2  2026-06-01     0   1535   20대     1   860.08        6     효성인텔리안 앞
3  2026-06-01     0   1650   20대     1   509.69        6      중계근린공원내
4  2026-06-01     0   2271   20대     1   931.08        8   내방역 8번출구 앞

In [235]:
df_rental.head()

  대여소번호          대여소  자치구         위도          경도  거치대수
0   102   망원역 1번출구 앞  마포구  37.555649  126.910629    15
1   103   망원역 2번출구 앞  마포구  37.554951  126.910835    14
2   104   합정역 1번출구 앞  마포구  37.550629  126.914986    13
3   105   합정역 5번출구 앞  마포구  37.550007  126.914825     5
4   106   합정역 7번출구 앞  마포구  37.548645  126.912827    12

In [238]:
df_month.to_csv('data/월별_공공자전거.csv', index=False, encoding='utf-8-sig')
df_date.to_csv('data/일별_공공자전거.csv', index=False, encoding='utf-8-sig')
df_time.to_csv('data/시간별_공공자전거.csv', index=False, encoding='utf-8-sig')
df_rental.to_csv('data/공공자전거_대여소.csv', index=False, encoding='utf-8-sig')

print('데이터 저장 완료!')

데이터 저장 완료!

In [322]:
df_time_re = pd.read_csv('data/시간별_공공자전거.csv')
df_time_re.head()

         대여일자  대여시간  대여소번호            대여소   연령대   이동거리(M)  이용시간(분)  이용건수
0  2026-06-01    15   4536      양천해누리체육공원  ~10대  29190.95      367    17
1  2026-06-01    17   1195  코오롱One&Only타워   30대  14278.76       89    15
2  2026-06-01     8   2701  마곡나루역 5번출구 뒤편   30대  13796.66       79    14
3  2026-06-01    21   2728    마곡나루역 3번 출구   30대  22510.28      154    14
4  2026-06-01     8   2715    마곡나루역 2번 출구   30대  10496.95       60    13

In [323]:
df_time_re.rename(columns={'연령대코드': '연령대'}, inplace=True)
df_time_re.head()

         대여일자  대여시간  대여소번호            대여소   연령대   이동거리(M)  이용시간(분)  이용건수
0  2026-06-01    15   4536      양천해누리체육공원  ~10대  29190.95      367    17
1  2026-06-01    17   1195  코오롱One&Only타워   30대  14278.76       89    15
2  2026-06-01     8   2701  마곡나루역 5번출구 뒤편   30대  13796.66       79    14
3  2026-06-01    21   2728    마곡나루역 3번 출구   30대  22510.28      154    14
4  2026-06-01     8   2715    마곡나루역 2번 출구   30대  10496.95       60    13

In [324]:
df_time_re.head()

         대여일자  대여시간  대여소번호            대여소   연령대   이동거리(M)  이용시간(분)  이용건수
0  2026-06-01    15   4536      양천해누리체육공원  ~10대  29190.95      367    17
1  2026-06-01    17   1195  코오롱One&Only타워   30대  14278.76       89    15
2  2026-06-01     8   2701  마곡나루역 5번출구 뒤편   30대  13796.66       79    14
3  2026-06-01    21   2728    마곡나루역 3번 출구   30대  22510.28      154    14
4  2026-06-01     8   2715    마곡나루역 2번 출구   30대  10496.95       60    13

In [249]:
# df_time_re = df_time_re.loc[:, ~df_time_re.columns.duplicated()]
# df_time_re

               대여일자  대여시간  대여소번호  연령대  이용건수  이동거리(M)  이용시간(분)            대여소
0        2026-06-01     0   1028  20대     1   769.67        4    포레스 주상복합 빌딩
1        2026-06-01     0   1150  20대     1  1549.49        9       송정역 1번출구
2        2026-06-01     0   1535  20대     1   860.08        6       효성인텔리안 앞
3        2026-06-01     0   1650  20대     1   509.69        6        중계근린공원내
4        2026-06-01     0   2271  20대     1   931.08        8     내방역 8번출구 앞
...             ...   ...    ...  ...   ...      ...      ...            ...
3660169  2026-06-30    23   4217  20대     1  2832.43       82     한강공원 망원나들목
3660170  2026-06-30    23   4622  30대     1   586.79        7  한강중학교 앞 버스정류장
3660171  2026-06-30    23   4217  20대     1  2999.47       82     한강공원 망원나들목
3660172  2026-06-30    23   3759  30대     1   583.45        2         이대서울병원
3660173  2026-06-30    23   2368  40대     1   740.23        7  도곡동 경남아파트 건너편

[3660174 rows x 8 columns]

In [325]:
df_time_re = df_time_re.groupby(['대여일자', '대여시간', '대여소번호', '대여소', '연령대', '이동거리(M)', '이용시간(분)'], as_index=False)['이용건수'].sum().sort_values(['대여일자', '이용건수'],ascending=[True, False])

In [326]:
df_time_re.head(5)

              대여일자  대여시간  대여소번호            대여소   연령대   이동거리(M)  이용시간(분)  이용건수
64630   2026-06-01    15   4536      양천해누리체육공원  ~10대  29190.95      367    17
76353   2026-06-01    17   1195  코오롱One&Only타워   30대  14278.76       89    15
27281   2026-06-01     8   2701  마곡나루역 5번출구 뒤편   30대  13796.66       79    14
120429  2026-06-01    21   2728    마곡나루역 3번 출구   30대  22510.28      154    14
27390   2026-06-01     8   2715    마곡나루역 2번 출구   30대  10496.95       60    13

In [281]:
df_time_re.to_csv('data/시간별_공공자전거.csv', index=False, encoding='utf-8-sig')

print('데이터 저장 완료')

데이터 저장 완료

In [392]:
df_date_re = pd.read_csv('data/서울특별시 공공자전거 이용정보(일별)_2606.csv')
df_date_re.head()

,대여일자,대여소번호,대여소,대여구분코드,성별,연령대,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,2026-06-01,736,736. 오솔길공원,정기권,NaN,~10대,1,42.99,0.39,1670.26,36
1,2026-06-01,939,939. 은평구청 교차로,정기권,NaN,~10대,1,39.05,0.35,1516.98,12
2,2026-06-01,1044,1044. 굽은다리역,정기권,NaN,~10대,1,67.58,0.61,2625.35,17
3,2026-06-01,1152,1152. 마곡역교차로,정기권,NaN,~10대,1,4.54,0.04,176.30,2
4,2026-06-01,2269,2269. 주홍교 하부,정기권,NaN,~10대,1,33.28,0.30,1293.01,11

In [393]:
df_date_re = df_date_re.drop(['대여구분코드', '성별', '운동량', '탄소량'], axis=1)
df_date_re.head()

         대여일자  대여소번호            대여소   연령대   이용건수  이동거리(M)  이용시간(분)
0  2026-06-01    736     736. 오솔길공원  ~10대      1  1670.26       36
1  2026-06-01    939  939. 은평구청 교차로  ~10대      1  1516.98       12
2  2026-06-01   1044    1044. 굽은다리역  ~10대      1  2625.35       17
3  2026-06-01   1152   1152. 마곡역교차로  ~10대      1   176.30        2
4  2026-06-01   2269   2269. 주홍교 하부  ~10대      1  1293.01       11

In [394]:
df_date_re[['대여소번호', '대여소']] = df_date_re['대여소'].str.extract(
    r'^(\d+)\.\s*(.*)$'
)

df_date_re['대여소번호'] = pd.to_numeric(
    df_date_re['대여소번호'],
    errors='coerce'
)

df_date_re['대여소'] = df_date_re['대여소'].str.strip()

df_date_re.head()

         대여일자   대여소번호       대여소   연령대   이용건수  이동거리(M)  이용시간(분)
0  2026-06-01   736.0     오솔길공원  ~10대      1  1670.26       36
1  2026-06-01   939.0  은평구청 교차로  ~10대      1  1516.98       12
2  2026-06-01  1044.0     굽은다리역  ~10대      1  2625.35       17
3  2026-06-01  1152.0    마곡역교차로  ~10대      1   176.30        2
4  2026-06-01  2269.0    주홍교 하부  ~10대      1  1293.01       11

In [395]:
df_date_re.isna().sum()

대여일자       0
대여소번호      8
대여소        8
연령대        0
 이용건수      0
이동거리(M)    0
이용시간(분)    0
dtype: int64

In [397]:
df_date_re.isna().sum()

대여일자       0
대여소번호      0
대여소        0
연령대        0
 이용건수      0
이동거리(M)    0
이용시간(분)    0
dtype: int64

In [398]:
df_date_re['대여소번호'] = df_date_re['대여소번호'].astype('Int64')
df_date_re.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2107231 entries, 0 to 2107238
Data columns (total 7 columns):
 #   Column   Dtype
---  ------   -----
 0   대여일자     object
 1   대여소번호    Int64
 2   대여소      object
 3   연령대      object
 4    이용건수    int64
 5   이동거리(M)  float64
 6   이용시간(분)  int64
dtypes: Int64(1), float64(1), int64(2), object(3)
memory usage: 130.6+ MB

In [399]:
df_date_re.head()

         대여일자  대여소번호       대여소   연령대   이용건수  이동거리(M)  이용시간(분)
0  2026-06-01    736     오솔길공원  ~10대      1  1670.26       36
1  2026-06-01    939  은평구청 교차로  ~10대      1  1516.98       12
2  2026-06-01   1044     굽은다리역  ~10대      1  2625.35       17
3  2026-06-01   1152    마곡역교차로  ~10대      1   176.30        2
4  2026-06-01   2269    주홍교 하부  ~10대      1  1293.01       11

In [400]:
df_date_re.columns = df_date.columns.str.strip()
print(df_date.columns.tolist())

['대여일자', '대여소번호', '대여소', '연령대', '이동거리(M)', '이용시간(분)', '이용건수']

In [401]:
df_date_re[['이용시간(분)', '이동거리(M)']].head(20)

    이용시간(분)  이동거리(M)
0   1670.26        1
1   1516.98        1
2   2625.35        1
3    176.30        1
4   1293.01        1
5   1758.36        2
6    762.29        1
7    424.38        1
8    658.19        1
9    463.45        1
10   563.62        1
11   833.56        1
12  2261.96        1
13  1025.33        1
14  1974.86        1
15  2823.61        1
16   492.37        1
17  1651.14        1
18  2138.98        1
19  1143.06        1

In [402]:
df_date_re['이용시간(분)'], df_date_re['이동거리(M)'] = (df_date_re['이동거리(M)'],df_date_re['이용시간(분)'])
df_date_re[['이용시간(분)', '이동거리(M)']].head()

   이용시간(분)  이동거리(M)
0        1  1670.26
1        1  1516.98
2        1  2625.35
3        1   176.30
4        1  1293.01

In [403]:
df_date_re.head()

         대여일자  대여소번호       대여소   연령대  이동거리(M)  이용시간(분)  이용건수
0  2026-06-01    736     오솔길공원  ~10대  1670.26        1    36
1  2026-06-01    939  은평구청 교차로  ~10대  1516.98        1    12
2  2026-06-01   1044     굽은다리역  ~10대  2625.35        1    17
3  2026-06-01   1152    마곡역교차로  ~10대   176.30        1     2
4  2026-06-01   2269    주홍교 하부  ~10대  1293.01        1    11

In [404]:
df_date_re = df_date_re.groupby(['대여일자', '대여소번호', '대여소', '연령대', '이용시간(분)', '이동거리(M)'], as_index=False)['이용건수'].sum().sort_values(['대여일자', '이용건수'],ascending=[True, False])

In [405]:
df_date_re.head()

             대여일자  대여소번호           대여소  연령대  이용시간(분)    이동거리(M)  이용건수
73809  2026-06-01   5891  한강버스 여의도 선착장  20대       31  169799.86  1238
71870  2026-06-01   5515   한강버스 망원 선착장  50대       15  117139.89  1169
73874  2026-06-01   5891  한강버스 여의도 선착장   기타       25  133366.63  1152
71824  2026-06-01   5515   한강버스 망원 선착장  20대       33  155084.54  1066
70691  2026-06-01   5153   한강버스 뚝섬 선착장  20대       22  117073.44   932

In [406]:
df_date_re.to_csv('data/일별_공공자전거.csv', index=False, encoding='utf-8-sig')

In [2]:
df_time = pd.read_csv('data/시간별_공공자전거.csv')
df_time.head()

         대여일자  대여시간  대여소번호            대여소   연령대   이동거리(M)  이용시간(분)  이용건수
0  2026-06-01    15   4536      양천해누리체육공원  ~10대  29190.95      367    17
1  2026-06-01    17   1195  코오롱One&Only타워   30대  14278.76       89    15
2  2026-06-01     8   2701  마곡나루역 5번출구 뒤편   30대  13796.66       79    14
3  2026-06-01    21   2728    마곡나루역 3번 출구   30대  22510.28      154    14
4  2026-06-01     8   2715    마곡나루역 2번 출구   30대  10496.95       60    13

In [4]:
df_time.head()

         대여일자  대여시간  대여소번호            대여소   연령대   이동거리(M)  이용시간(분)  이용건수
0  2026-06-01    15   4536      양천해누리체육공원  ~10대  29190.95      367    17
1  2026-06-01    17   1195  코오롱One&Only타워   30대  14278.76       89    15
2  2026-06-01     8   2701  마곡나루역 5번출구 뒤편   30대  13796.66       79    14
3  2026-06-01    21   2728    마곡나루역 3번 출구   30대  22510.28      154    14
4  2026-06-01     8   2715    마곡나루역 2번 출구   30대  10496.95       60    13